import 'package:get/get.dart';

class Traduction extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'titre': 'AfriCulture',
          'categorie': 'category',
          'c1': 'Art',
          'c2': 'Clothes',
          'c3': 'Eating',
          'c4': 'Furniture',
          'c5': 'Decoration',
          'c6': 'Others',
          'panier': 'my cart',
          'vider_panier': 'CLEAR THE BASKET',
          'passer_commande': 'To order',
          'panier_vide': 'the basket is empty',
          'selection_quantite': 'Select quantity',
          'acheter_maintenant': 'BUY NOW',
          'ajouter_panier': 'ADD TO CART',
          'description': 'description',
          'en_stock': 'En Stock',
          'plus_en_stock': 'Plus en Stock',
          'compte': 'Account',
          'compte_message': 'You do not have an account',
          'connexion': 'Connection',
          'authentifier': 'Authenticate',
          'deja_compte': 'I already have an account',
          'parametres': 'settings',
          'favoris': 'Favorites',
          'commande': 'Orders',
          'commande_speciale': 'Special order',
          'adresse': 'Addresses',
          'langues': 'Languages',
          'politique': 'Privacy Policy',
          'profil': 'Profile',
          'historique_commande': 'Order history',
          'ajouter': 'Add',
          'nouvelle_adresse': 'New address',
          'liste_adresse': 'List of addresses',
          'titre_adresse': 'Title',
          'titre_adresse_message': 'Titre vide',
          'pays': 'Pays',
          'pays_message': '',
          'etat_province': 'State/Province',
          'etat_province_message': '',
          'ville': 'Ville',
          'ville_message': 'Ville',
          'commune': 'Municipality / District',
          'commune_message': 'Commune / Arrondissement',
          'quartier': 'Piece',
          'quartier_message': 'Quartier',
          'avenue': 'Avenue or Street',
          'avenue_message': 'Avenue ou Rue',
          'numero': 'Number',
          'numero_message': 'Numéro',
          'code_postal': 'Postal code',
          'code_postal_message': 'Code postal',
          'nos_produit': 'Our produces',
          'profil_vendeur': 'Profile Vendor',
          'profil_vendeur_text':
              'Vous permet de vendre vos produits dans notre platforme, pour ce faire vous devez crée un compte business dans notre platforme pour bénéficier de ce service, commencez dès maintenant.',
          'commencer': 'Commencer',
          'deja_compte_vendeur': 'Vous avez déjà un compte ?',
          'code_legal': 'Legal code',
          'mot_de_passe': 'Pass world',
          'mot_de_passe_message': 'Veuillez saisir votre Mot de passe',
          'continuer': 'Continuer',
          'bloquer_compte_vendeur': '',
          'examen_dossier': 'Examen du dossier en cours...',
          'recherche': 'Search',
          'boutique:': 'Boutique',
          'poid:': 'Poids',
          'disponible:': 'Disponibilité',
        },
        'fr_FR': {
          'titre': 'AfriCulture',
          'categorie': 'categorie',
          'c1': 'Art',
          'c2': 'Vetements',
          'c3': 'Alimentaire',
          'c4': 'Mobilier',
          'c5': 'Décoration',
          'c6': 'Autres',
          'panier': 'mon panier',
          'vider_panier': 'VIDER LE PANIER',
          'passer_commande': 'Passer la commande',
          'panier_vide': 'Le panier est vide',
          'selection_quantite': 'Sélectionnez la quantite',
          'acheter_maintenant': 'ACHETER MAINTENANT',
          'ajouter_panier': 'AJOUTER AU PANIER',
          'description': 'description',
          'en_stock': 'En Stock',
          'plus_en_stock': 'Plus en Stock',
          'compte': 'Compte',
          'compte_message': 'Vous n\'avez pas de compte',
          'connexion': 'Connexion',
          'authentifier': 'S\'authentifier',
          'deja_compte': 'J\'ai déjà un compte',
          'parametres': 'Parametres',
          'favoris': 'Favoris',
          'commande': 'Commandes',
          'commande_speciale': 'Commande spéciale',
          'adresse': 'Adresses',
          'langues': 'Langues',
          'politique': 'Politique et confidencialité',
          'profil': 'Profil',
          'historique_commande': 'Historique de commandes',
          'ajouter': 'Ajouter',
          'nouvelle_adresse': 'Nouvelle adresse',
          'liste_adresse': 'Liste des adresses',
          'titre_adresse': 'Titre',
          'titre_adresse_message': 'Titre vide',
          'pays': 'Pays',
          'pays_message': '',
          'etat_province': 'Etat / Province',
          'etat_province_message': 'Vide',
          'ville': 'Ville',
          'ville_message': 'Ville vide',
          'commune': 'Commune / Arrondissement',
          'commune_message': 'Commune / Arrondissement',
          'quartier': 'Quartier',
          'quartier_message': 'Quartier vide',
          'avenue': 'Avenue ou Rue',
          'avenue_message': 'Avenue ou Rue vide',
          'numero': 'Numéro',
          'numero_message': 'Numéro vide',
          'code_postal': 'Code postal',
          'code_postal_message': 'Code postal vide',
          'nos_produit': 'Nos produits',
          'profil_vendeur': 'Profil Vendeur',
          'profil_vendeur_text':
              'Vous permet de vendre vos produits dans notre platforme, pour ce faire vous devez crée un compte business dans notre platforme pour bénéficier de ce service, commencez dès maintenant.',
          'commencer': 'Commencer',
          'deja_compte_vendeur': 'Vous avez déjà un compte ?',
          'code_legal': 'Code legal',
          'mot_de_passe': 'Mot de passe',
          'mot_de_passe_message': 'Veuillez saisir votre Mot de passe',
          'continuer': 'Continuer',
          'bloquer_compte_vendeur':
              'Si vous voyez ce message ce que votre boutique a été momentanement bloqué, veuillez contacter le service de AfricCulture pour plus d\'information.',
          'examen_dossier': 'Examen du dossier en cours...',
          'recherche': 'Recherche',
          'boutique:': 'Boutique',
          'poid:': 'Poids',
          'disponible:': 'Disponibilité',
        }
      };
}
